[package]
name = "threshold-signatures"
description = "Threshold Signatures"
repository = "https://github.com/near/threshold-signatures"
version = "0.8.0"
edition = "2021"
license = "MIT"

[dependencies]
auto_ops = "0.3.0"
byteorder = "1.5.0"
digest = "0.10.7"
ecdsa = { version = "0.16.8", features = ["digest", "hazmat"] }
elliptic-curve = { version = "0.13.5", features = ["serde"] }
frost-core = { version = "2.1.0", default-features = false, features = ["serialization", "std", "internals"] }
frost-ed25519 = { version = "2.1.0", default-features = false, features = ["serialization", "std"] }
frost-secp256k1 = { version = "2.1.0", default-features = false, features = ["serialization", "std"] }
futures = "0.3.31"
itertools = "0.14.0"
k256 = { version = "0.13.1", features = ["sha256", "ecdsa", "serde"]}
keccak = "0.1.5"
rand = "0.9.0"
# updating this one requires quite a few code changes
rand_core = { version = "0.6.4", features = ["getrandom"] }
rmp-serde = "1.1.2"
serde = { version = "1.0.175", features = ["derive"] }
sha2 = "0.10.9"
sha3 = "0.10.8"
smol = "2.0.2"
subtle = "2.5.0"
thiserror = "2.0.12"
zeroize = "1.8.1"
