[package]
name = "threshold-signatures"
description = "Threshold Signatures"
repository = "https://github.com/near/threshold-signatures"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
auto_ops = "0.3.0"
blstrs = "0.7.1"
borsh = "1.5.7"
byteorder = "1.5.0"
derive_more = { version = "2.0.1", features= ["deref", "deref_mut"]}
digest = "0.10.7"
ecdsa = { version = "0.16.9", features = ["digest", "hazmat"] }
elliptic-curve = { version = "0.13.8", features = ["serde"] }
frost-core = { version = "2.2.0", default-features = false, features = [
  "serialization",
] }
frost-ed25519 = { version = "2.2.0", default-features = false, features = [
  "serialization",
] }
frost-secp256k1 = { version = "2.2.0", default-features = false, features = [
  "serialization",
] }
futures = "0.3.31"
futures-lite = "2.6.1"
hex = "0.4.3"
hkdf = "0.12.4"
k256 = { version = "0.13.4", default-features = false, features = [
  "sha256",
  "ecdsa",
  "serde",
  "hash2curve",
] }
keccak = "0.1.5"
# This one cannot be upgraded to remain compatible with frost-core
rand_core = { version = "0.6.4" }
rmp-serde = "1.3.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11.19"
serde_json = "1.0.145"
sha2 = "0.10.9"
sha3 = "0.10.8"
subtle = "2.6.1"
thiserror = "2.0.17"
zeroize = "1.8.2"

[features]
default = ["actively_secure_robust_ecdsa"]
actively_secure_robust_ecdsa = []

[dev-dependencies]
criterion = "0.7.0"
bincode = { version = "2.0.1", features = ["serde"] }
rand = "0.8.5"
rand_core = { version = "0.6.4", features = ["getrandom"]}

[[bench]]
name = "main"
harness = false

[profile.test-release]
inherits = "release"
overflow-checks = true
debug = true

[lints.clippy]
# We might revisit these exceptions in the future
missing-const-for-fn = "allow"
trait-duplication-in-bounds = "allow"
missing-errors-doc = "allow"
similar-names = "allow"
many-single-char-names = "allow"
must-use-candidate = "allow"
return-self-not-must-use = "allow"

# TODO: this also hit too many cases https://github.com/near/threshold-signatures/issues/122
# should be removed
indexing-slicing = "allow"

# Part of clippy restriction group
panic = "deny"
panic-in-result-fn = "warn"
unwrap-used = "warn"

# Lint groups used
nursery = {level = "warn", priority = -1}
pedantic = {level = "warn", priority = -1}