[package]
name = "threshold-signatures"
description = "Threshold Signatures"
repository = "https://github.com/near/threshold-signatures"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
auto_ops = "0.3.0"
blstrs = "0.7.1"
borsh = "1.5.7"
byteorder = "1.5.0"
digest = "0.10.7"
ecdsa = { version = "0.16.8", features = ["digest", "hazmat"] }
elliptic-curve = { version = "0.13.5", features = ["serde"] }
frost-core = { version = "2.1.0", default-features = false, features = [
  "serialization",
  "std",
] }
frost-ed25519 = { version = "2.1.0", default-features = false, features = [
  "serialization",
  "std",
] }
frost-secp256k1 = { version = "2.1.0", default-features = false, features = [
  "serialization",
  "std",
] }
futures = "0.3.31"
hex = "0.4.3"
hkdf = "0.12.4"
itertools = "0.14.0"
k256 = { version = "0.13.1", features = [
  "sha256",
  "ecdsa",
  "serde",
  "hash2curve",
] }
keccak = "0.1.5"
# This one cannot be upgraded to remain compatible with frost-core
rand_core = { version = "0.6.4", features = ["getrandom"] }
rmp-serde = "1.1.2"
serde = { version = "1.0.175", features = ["derive"] }
serde_bytes = "0.11.17"
serde_json = "1.0.143"
sha2 = "0.10.9"
sha3 = "0.10.8"
smol = "2.0.2"
subtle = "2.5.0"
thiserror = "2.0.16"
zeroize = "1.8.1"

[features]
default = ["actively_secure_robust_ecdsa"]
actively_secure_robust_ecdsa = []

[dev-dependencies]
criterion = "0.7.0"
bincode = { version = "2.0.1", features = ["serde"] }

[[bench]]
name = "main"
harness = false

[profile.test-release]
inherits = "release"
overflow-checks = true
debug = true

[lints.clippy]
# We might revisit these exceptions in the future
missing-const-for-fn = "allow"
trait-duplication-in-bounds = "allow"
missing-errors-doc = "allow"
similar-names = "allow"
many-single-char-names = "allow"
must-use-candidate = "allow"

# TODO: remove this one https://github.com/near/threshold-signatures/issues/119
cast-possible-truncation = "allow"
# TODO: this detected some function which might panic https://github.com/near/threshold-signatures/issues/120
missing-panics-doc = "allow"
# TODO: this also hit too many cases https://github.com/near/threshold-signatures/issues/122
indexing-slicing = "allow"

# Part of clippy restriction
panic = "deny"
# TODO: enable this one
# panic-in-result-fn = "warn"

# Lint groups used
nursery = {level = "warn", priority = -1}
pedantic = {level = "warn", priority = -1}