[package]
name = "cait-sith"
description = "Threshold ECDSA via Triples"
repository = "https://github.com/cronokirby/cait-sith"
version = "0.8.0"
edition = "2021"
license = "MIT"

[dependencies]
auto_ops = "0.3.0"
byteorder = "1.5.0"
digest = "0.10.7"
ecdsa = { version = "0.16.8", features = ["digest", "hazmat"] }
elliptic-curve = { version = "0.13.5", features = ["serde"] }
event-listener = "2.5.3"
frost-core = { version = "2.1.0", default-features = false, features = ["serialization", "std", "internals"] }
frost-ed25519 = { version = "2.1.0", default-features = false, features = ["serialization", "std"] }
frost-secp256k1 = { version = "2.1.0", default-features = false, features = ["serialization", "std"] }
futures = "0.3.31"
itertools = "0.14.0"
k256 = { version = "0.13.1", features = ["sha256", "ecdsa", "serde"], optional = true }
keccak = "0.1.5"
rand = "0.9.0"
rand_core = { version = "0.6.4", features = ["getrandom"] }
rmp-serde = "1.1.2"
serde = { version = "1.0.175", features = ["derive"] }
sha2 = "0.10.8"
sha3 = "0.10.8"
smol = "1.3.0"
subtle = "2.5.0"
zeroize = "1.8.1"

[dev-dependencies]
criterion = "0.4"
easy-parallel = "3.2.0"
haisou-chan = { git = "https://github.com/cronokirby/haisou-chan", rev = "d28c46e51acfcb818236caae293f6e56dff41ad2" }
structopt = "0.3.26"
k256 = { version = "0.13.1", features = ["sha256", "ecdsa", "serde"], optional = false }

[features]
k256 = ["dep:k256"]

[[example]]
name = "network-benches"
path = "examples/network-benches.rs"
required-features = ["k256"]
