[tasks.check-all]
description = "Run all checks"
dependencies = ["fmt", "check", "clippy", "test"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features", "--all-targets", "--locked", "--", "-D", "warnings"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.test]
command = "cargo"
args = [
  "test",
  "--profile",
  "test-release",
  "--all-features",
  "--all-targets",
  "--locked",
]

[tasks.fmt-fix]
command = "cargo"
args = ["fmt"]
